language: node_js
node_js:
- '8'
sudo: required
dist: trusty
env:
  global:
    secure: URFvhD9K2O1lr4oUB5GGCBUXk1nPHGF0BP+yUC+xn4WpkidPclKGOZtZWUS9wipywmMMWV3mNBQTKi5+YRMcXdOGNZ7P8xDqnNkHvSsxUrrExjg45cLra2AVT2kfe39bcGFYx+HPdu3au1kSmvjyyJaRQQ6KkZFykvn2HC3dF9oGMwNIUBRyZbFCaFdUBcSxJYHs+GgHKJz/1dUhR5+kL5welloc/0aUWjU7AQNunMD3hKuJHoxcqj78ksOxr0vI/XwrVGMFsZIAOb0KsJCirXeUO15eaAzRMSr4A4Ut8x9VVR15OtEcar+qfRA6fL2m5vQTSmV3BM/4RkGN7CruUnRk55fRPSRrnwUWhPhOXuOCUsQd7jiCvyhUragNWM4GHYB4GrFf83CaOPcuX8Shu9rmTllL07A4aXVyOyBMI+x2QzfyeF1nrQKn4FR3Ea2l43ayF4oaz9sDLnKSI4FH4k8riNvDeh2YD4Z3PI1YybQg2x82QiwZ+4YBofSRcNx6NjUj7Tl+LFpzjlcJiyoe1XWocr0DHfo405OYqYFxPijykc7zbqRa1p1I4NQNLif7AgbIeb2wp5ACBUFYZxv4YNL0PPLHjMSgVOR/knOTyPsnaGPU5/WTLJs05hax/hOqS371QhKy1jxdrfqjgOqIxOGP63oUScv+P6NZePwkDjY=
branches:
  only:
  - master
before_install:
- npm install -g gitbook-cli
install: true
script: "./build"
deploy:
- provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: pages
  repo: hilanderas/hilanderas.github.io
  target-branch: master
  github-token: "$GITHUB_TOKEN"
  on:
    branch: master
